apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stock-app-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - stock-app.local
      secretName: stock-app-tls
  rules:
    - host: stock-app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stock-app-service
                port:
                  number: 80

